# Generated by Django 3.1.2 on 2020-11-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessons.chat'),
            preserve_default=False,
        ),
    ]
