# Generated by Django 3.1.2 on 2020-11-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='chat',
            new_name='lesson_chat',
        ),
    ]
